// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input C:/Users/waiwa/Desktop/solid/fontopoSOLID-Regular.png --output C:/Users/waiwa/Desktop/solid --no-ascii False --unicode-glyphs  --format mono16 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_fontopoSOLID_Regular_length;
extern const uint8_t  font_fontopoSOLID_Regular[3581];
