// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input C:/Users/waiwa/OneDrive/自作キーボード/設計/エンブレム/Earth87lcd_logo2.png --output C:/Users/waiwa/OneDrive/自作キーボード/設計/エンブレム --format rgb565 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_Earth87lcd_logo2_length;
extern const uint8_t  gfx_Earth87lcd_logo2[6849];
